
#Common Config (: 
#Cool stuff here.
[" ROGUE CONFIG"]
	#Override Rogue Class with custom values & bug fixes HIGHLY RECOMMENDED
	enableTrueInvis = true
	#Max Health for Rogue
	#Range: 1.0 ~ 1000.0
	rogue_max_health = 16.0
	#Luck for Rogue
	#Range: 0.0 ~ 100.0
	rogue_luck = 1.0
	#Attack Damage for Rogue
	#Range: 0.0 ~ 100.0
	rogue_damage = 2.0
	#Speed for Rogue
	#Range: 0.0 ~ 100.0
	rogue_speed = 0.12
	#Attack Speed for Rogue
	#Range: 0.0 ~ 100.0
	rogue_attack_speed = 4.2
	#Armorfor Rogue
	#Range: 0.0 ~ 100.0
	rogue_armor = 0.0
	#Starting Helmet for Rogue
	rogue_helmet = "dungeons_and_combat:rogue_helmet"
	#Starting Chestplate for Rogue
	rogue_chestplate = "dungeons_and_combat:rogue_chestplate"
	#Starting Leggings for Rogue
	rogue_leggings = "dungeons_and_combat:rogue_leggings"
	#Starting Boots for Rogue
	rogue_boots = "dungeons_and_combat:rogue_boots"

[" Bounty Hunter CONFIG"]
	#Max Health for bounty hunter
	#Range: 1.0 ~ 1000.0
	bounty_max_health = 18.0
	#Luck for Rogue
	#Range: 0.0 ~ 100.0
	bounty_luck = 1.0
	#Attack Damage for bounty hunter
	#Range: 0.0 ~ 100.0
	bounty_damage = 1.600000023841858
	#Speed for bounty hunter
	#Range: 0.0 ~ 100.0
	bounty_speed = 0.12
	#Attack Speed for bounty hunter
	#Range: 0.0 ~ 100.0
	bounty_attack_speed = 3.95
	#Armor for bounty hunter
	#Range: 0.0 ~ 100.0
	bounty_armor = 0.0
	#Starting Helmet for bounty hunter
	bounty_helmet = "dungeons_and_combat:bounty_hunter_helmet"
	#Starting Chestplate for bounty hunter
	bounty_chestplate = "dungeons_and_combat:bounty_hunter_chestplate"
	#Starting Leggings for bounty hunter
	bounty_leggings = "dungeons_and_combat:bounty_hunter_leggings"
	#Starting Boots for bounty hunter
	bounty_boots = "dungeons_and_combat:bounty_hunter_boots"

[" Oni Slayer CONFIG"]
	#Max Health for oni slayer
	#Range: 1.0 ~ 1000.0
	oni_health = 18.0
	#Luck for oni slayer
	#Range: 0.0 ~ 100.0
	oni_luck = 1.0
	#Attack Damage for oni slayer
	#Range: 0.0 ~ 100.0
	oni_damage = 1.2000000476837158
	#Speed for oni slayer
	#Range: 0.0 ~ 100.0
	oni_speed = 0.095
	#Attack Speed for oni slayer
	#Range: 0.0 ~ 100.0
	oni_attack_speed = 4.2
	#Armor for oni slayer
	#Range: 0.0 ~ 100.0
	oni_armor = 0.0
	#Starting Helmet for oni slayer
	oni_helmet = "dungeons_and_combat:oni_slayer_helmet"
	#Starting Chestplate for oni slayer
	oni_chestplate = "dungeons_and_combat:oni_slayer_chestplate"
	#Starting Leggings for oni slayer
	oni_leggings = "dungeons_and_combat:oni_slayer_leggings"
	#Starting Boots for oni slayer
	oni_boots = "dungeons_and_combat:oni_slayer_boots"

[" Forgotten Knight CONFIG"]
	#Max Health for Forgotten Knight
	#Range: 1.0 ~ 1000.0
	FORGOTTEN_health = 20.0
	#Luck for Forgotten Knight
	#Range: 0.0 ~ 100.0
	FORGOTTEN_luck = 0.0
	#Attack Damage for Forgotten Knight
	#Range: 0.0 ~ 100.0
	FORGOTTEN_damage = 1.399999976158142
	#Speed for Forgotten Knight
	#Range: 0.0 ~ 100.0
	FORGOTTEN_speed = 0.095
	#Attack Speed for Forgotten Knight
	#Range: 0.0 ~ 100.0
	FORGOTTEN_attack_speed = 3.95
	#Armor for Forgotten Knight
	#Range: 0.0 ~ 100.0
	FORGOTTEN_armor = 2.0
	#Starting Helmet for Forgotten Knight
	FORGOTTEN_helmet = "dungeons_and_combat:forgotten_knight_helmet"
	#Starting Chestplate for Forgotten Knight
	FORGOTTEN_chestplate = "dungeons_and_combat:forgotten_knight_chestplate"
	#Starting Leggings for Forgotten Knight
	FORGOTTEN_leggings = "dungeons_and_combat:forgotten_knight_leggings"
	#Starting Boots for Forgotten Knight
	FORGOTTEN_boots = "dungeons_and_combat:forgotten_knight_boots"

["  EXILED CONFIG"]
	#Max Health for Exiled
	#Range: 1.0 ~ 1000.0
	EXILED_health = 18.0
	#Luck for Exiled
	#Range: 0.0 ~ 100.0
	EXILED_luck = 1.0
	#Attack Damage for Exiled
	#Range: 0.0 ~ 100.0
	EXILED_damage = 1.0
	#Speed for Exiled
	#Range: 0.0 ~ 100.0
	EXILED_speed = 0.11
	#Attack Speed for Exiled
	#Range: 0.0 ~ 100.0
	EXILED_attack_speed = 3.95
	#Armor for Exiled
	#Range: 0.0 ~ 100.0
	EXILED_armor = 0.0
	#Starting Helmet for Exiled
	EXILED_helmet = "dungeons_and_combat:exiled_helmet"
	#Starting Chestplate for Exiled
	EXILED_chestplate = "dungeons_and_combat:exiled_chestplate"
	#Starting Leggings for Exiled
	EXILED_leggings = "minecraft:air"
	#Starting Boots for Exiled
	EXILED_BOOTS = "minecraft:air"

["  TITAN CONFIG"]
	#Max Health for Titan
	#Range: 1.0 ~ 1000.0
	TITAN_health = 28.0
	#Luck for Titan
	#Range: 0.0 ~ 100.0
	TITAN_luck = 0.0
	#Attack Damage for Titan
	#Range: 0.0 ~ 100.0
	TITAN_damage = 1.0
	#Speed for Titan
	#Range: 0.0 ~ 100.0
	TITAN_speed = 0.085
	#Attack Speed for Titan
	#Range: 0.0 ~ 100.0
	TITAN_attack_speed = 3.85
	#Armor for Titan
	#Range: 0.0 ~ 100.0
	TITAN_armor = 0.1
	#Starting Helmet for Titan
	TITAN_helmet = "dungeons_and_combat:titan_helmet"
	#Starting Chestplate for Titan
	TITAN_chestplate = "dungeons_and_combat:titan_chestplate"
	#Starting Leggings for Titan
	TITAN_leggings = "dungeons_and_combat:titan_leggings"
	#Starting Boots for Titan
	TITAN_boots = "dungeons_and_combat:titan_boots"
	#Toughness for Titan
	#Range: 0.0 ~ 100.0
	TITAN_toughness = 0.1

["VAGABOND CONFIG"]
	#Max Health for vagabond
	#Range: 1.0 ~ 1000.0
	vagabond_health = 20.0
	#Luck for vagabond
	#Range: 0.0 ~ 100.0
	vagabond_luck = 0.0
	#Attack Damage for vagabond
	#Range: 0.0 ~ 100.0
	vagabond_damage = 1.0
	#Speed for vagabond 
	#Range: 0.0 ~ 100.0
	vagabond_speed = 0.1
	#Attack Speed for vagabond 
	#Range: 0.0 ~ 100.0
	vagabond_attack_speed = 0.0
	#Starting Helmet for vagabond
	vagabond_helmet = "dungeons_and_combat:vagabond_helmet"
	#Starting Chestplate for vagabond
	vagabond_chestplate = "dungeons_and_combat:vagabond_chestplate"
	#Starting Leggings for vagabond
	vagabond_leggings = "dungeons_and_combat:vagabond_leggings"
	#Starting Boots for vagabond
	vagabond_boots = "dungeons_and_combat:vagabond_boots"

[" KAMATH BOSS CONFIG"]
	#Kamath's movement speed
	#Range: 0.0 ~ 100.0
	kamath_movement_speed = 0.3
	#Kamath's Health
	#Range: 0.0 ~ 100000.0
	kamath_max_health = 500.0
	#Kamath's armor
	#Range: 0.0 ~ 1000.0
	kamath_armor = 20.0
	#Kamath's damage 
	#Range: 0.0 ~ 1000.0
	kamath_attack_damage = 24.0
	#Kamath's Follow Range
	#Range: 0.0 ~ 1000.0
	kamath_follow_range = 64.0
	#Kamath's knockback resistance
	#Range: 0.0 ~ 1000.0
	kamath_knockback_resistance = 1.0
	#Kamath's attack knockback
	#Range: 0.0 ~ 1000.0
	kamath_attack_knockback = 1.0

["FRACTURED VEX"]
	#Fractured vex spawn weight
	#Range: 0 ~ 1000
	fractured_vex-spawn_weight = 100
	#Fractured vex spawn minimum amount
	#Range: 0 ~ 100
	fractured_vex-spawn_min = 10
	#Fractured vex spawn maximum amount
	#Range: 0 ~ 100
	fractured_vex-spawn_max = 30

